year = int(input("Enter the year: "))
genre = input("Enter the genre: ")
album = input("Enter the album: ")
song = input("Enter the song title: ")
artist = input("Enter the artist: ")

print("-----------------------------\n SONG DETAILS\n-----------------------------")
print(f"Year: {year}")
print(f"Genre: {genre}")
print(f"Album: {album}")
print(f"Song title: {song}")
print(f"Artist: {artist}")